version: '3'

services:

  web:
    build: ./docker-utils/web/
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8088:443"
    hostname: drupal-docker.local
    volumes:
      - ./:/var/www/html
    command: bash -c 'useradd -u 1000 www-data; nginx -g "daemon off;" && service nginx start && nginx -s reload'

  db:
    image: mysql:5.7
    ports:
      - "3388:3306"
      - "444:443"
    volumes:
      - ./docker-utils/databases:/var/lib/mysql
      - ./docker-utils/sqldump:/app/sqldump
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal_docker
      MYSQL_USER: drupal_docker_user
      MYSQL_PASSWORD: drupal_docker_pass
